version: '3'
services: 
    client:
        build: 
            context: ./client
        container_name: client
        ports: 
            - 8000:8000
        networks: 
            - frontend
    nginx:
        restart: always
        build:
            context: ./nginx
        container_name: nginx
        ports:
            - '3050:80'
        networks:
            - frontend

networks: 
    frontend

