version: 2.1
executors:
    docker_publisher:
        environment:
            CLIENT_IMAGE: mdecker84/cc_build_client
            NGINX_IMAGE: mdecker84/cc_build_nginx
        docker:
            - image: circleci/buildpack-deps:stretch
    docker-deploy:
        docker:
            - image: circleci/python:3.6.8
jobs:
    build:
        executor: docker-publisher
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build Docker image
                command: |
                    docker build -t $CLIENT_IMAGE:latest ./client
                    docker build -t $NGINX_IMAGE:latest ./nginx
            - run:
                name: Archive Docker image
                command: |
                    docker save -o image-client.tar $CLIENT_IMAGE
                    docker save -o image-nginx.tar $NGINX_IMAGE
            - persist_to_workspace:
                root: .
                paths:
                    - ./image-client.tar    
                    - ./image-nginx.tar
        publish-latest:
            executor: docker_publisher
            steps:
                - attach_workspace:
                    at: /tmp/workspace
                - setup_remote_docker
                - run:
                    name: Load archived Docker image
                    command: |
                        docker load -i /tmp/workspace/image-client.tar
                        docker load -i /tmp/workspace/image-nginx.tar
                - run:
                    name: Publish Docker Image to Docker Hub
                    command: |
                        echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_ID --password-stdin
                        docker push $CLIENT_IMAGE:latest
                        docker push $NGINX_IMAGE:latest

workflow:
    version: 2
    buiild-master:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
